# Generated by Django 5.0.2 on 2024-12-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emediapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Cardiologist(heart, blood vessels)', 'Cardiologist(blood vessels, heart)'), ('Dermatologists(Skin, nails, hair)', 'Dermatologists(skin, nails, hair)'), ('Pediatrician(care for children)', 'Pediatrician(care for children)'), ('Allergists/Immunologists', 'Allergists/Immunologists'), ('Optometrists( Specialist on eyes)', 'Optometrists( Specialist on eyes)'), ('Urologist(Bladder, urinary tract)', 'Urologist(Bladder, urinary tract)'), ('Neurosurgeon(Nervous system)', 'Neurosurgeon(Nervous system)'), ('Obstetrician(Women repro. health)', 'Obstetrician(Women repro health)'), ('Hematologists(blood, anaemia, sickle cell)', 'Hematologists(blood, anaemia, sickle cell)'), ('Emergency Medicine Specialists', 'Emergency Medicine Specialists'), ('Radiologists(X-rays, Ultrasounds)', 'Radiologists(X-rays, Ultrasounds)'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons')], default='', max_length=50),
        ),
    ]
